hydra:
  job:
    name: ${env.env_id}_s${seed}
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

seed: 0
max_steps: 400_000
buffer_size: 400_000
save_interval_steps: 100000
log_interval_steps: 10000

env:
  backend: gymnasium
  env_id: GraphSearch-v0
  num_envs: 4
  utd_ratio: 1.0
  asynchronous: True

  dmc: { obs_type: state }

encoder:
  embed_dim: 128
  num_layers: 1
  num_heads: 4
  learning_rate: 3e-4
  tabulate: True

world_model:
  latent_dim: 512
  value_dropout: 0.01
  num_value_nets: 5
  num_bins: 101
  symlog_min: -10
  symlog_max: 10
  symlog_obs: False
  simnorm_dim: 8
  learning_rate: 3e-4
  predict_continues: False
  dtype: float32
  max_grad_norm: 20
  tabulate: False

tdmpc2:
  # Planning
  mpc: True
  horizon: 1
  mppi_iterations: 6
  population_size: 512
  policy_prior_samples: 24
  num_elites: 64
  min_plan_std: 0
  max_plan_std: 2
  temperature: 1.0
  # Optimization
  batch_size: 256
  discount: 0.95
  rho: 0.5
  consistency_coef: 20
  reward_coef: 0.1
  continue_coef: 1.0
  value_coef: 0.1
  entropy_coef: 1e-4
  tau: 0.01
